pipeline:
  test:
    image: node:${NODE_VERSION}
    commands:
      - npm install
      - npm run build
      - npm run test
  publish:
    image: plugins/npm
    username: ${NPM_USERNAME}
    password: ${NPM_PASSWORD}
    email: ${NPM_EMAIL}
    when:
      matrix:
        NODE_VERSION: 6
matrix:
  NODE_VERSION:
    - 6
    - 7
    - 8
