image: node:7.7.0

before_script:
  - npm install

stages:
- build
- test

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
  - npm run build

test:
  stage: test
  script:
  - npm run test
